### PR TITLE
Kadane algorithm

### PR DESCRIPTION
**Pull request by akashmd7**

### CODE REVIEW

**Comment by VigneshKarthigeyan** [comment]
Assign possible minimum value to msf at line no.14 @akashmd7 
Assigning zero will fail if all the numbers are negative..

**Comment by InbasasiS** [comment]
Good Work @akashmd7 Note down the review comments
Move on to your next tasks

**Comment by akashmd7** [comment]
@VigneshKarthigeyan Yeah bro.. I'll make the changes..

**Comment by akashmd7** [comment]
@InbasasiS Okay bro

**Pull request merged**
