### PR TITLE
To upload article related details in db

### PR DESCRIPTION
**Pull request by GAYU-GITT**

### CODE REVIEW

**Comment by tamilarasumk731** [comment]
@GAYU-GITT can u split this into multiple files. Separate files for model and controller.

CC: @AkbarHabeeb @InbasasiS @smartsri18

**Comment by InbasasiS** [comment]
@GAYU-GITT Did you get chance to look the above comments?
cc: @tamilarasumk731 @AkbarHabeeb

**Comment by InbasasiS** [comment]
@GAYU-GITT any update here?

**Comment by AkbarHabeeb** [comment]
Im okie with the changes, u can pick any issue in QP-generator and solve them @GAYU-GITT

**Pull request merged**
