### PR TITLE
Linear regression

### PR DESCRIPTION
**Pull request by keerthu25**
First task completed

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
Nice @keerthu25. Good to see sklearn in practice. Can you show the following as well,
1. Display the convergence value of the parameter (theta/weight)
2. A graph showing squared error cost function against the number of iterations for theta.

These are to help you in learning the core part of it.

**Comment by keerthu25** [comment]
ok anna will do this...

**Comment by AkbarHabeeb** [comment]
@keerthu25 How's going

**Comment by AkbarHabeeb** [comment]
@keerthu25 Hello, Please let us know the status.

**Comment by InbasasiS** [comment]
closing since no update

**Pull request closed without merging**
