### PR TITLE
ruby arithmetic api

### PR DESCRIPTION
**Pull request by ThirukumaranPalani9080**

### CODE REVIEW

**Comment by InbasasiS** [comment]
@ThirukumaranPalani9080 Good work so far...You have initialised the num1 and num2 in the controller itself but it needs to passed as a params to the API
Check those...

**Comment by InbasasiS** [comment]
Refer this https://github.com/Team-Tomato/Learn/tree/master/Poomathi/arithmetic_operation

**Comment by InbasasiS** [comment]
@ThirukumaranPalani9080 Are you working in it?

**Comment by AkbarHabeeb** [comment]
Merging it for now @Inbasasi, if interested he can rise new PR

**Pull request merged**
