### PR TITLE
Subhiksha/task

### PR DESCRIPTION
**Pull request by subhiksha491**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@subhiksha491 Can you change your files alone.

**Comment by subhiksha491** [comment]
Ok anna

**Comment by tamilarasumk731** [comment]
@subhiksha491 Why does the PR contains your classmate files?

cc: @AkbarHabeeb

**Comment by subhiksha491** [comment]
Anna, that's my previous pull request.i created a new pull request as
python tasks today.

**Comment by AkbarHabeeb** [comment]
@subhiksha491 Since the new PR was merged. Closing this duplicate.

**Pull request closed without merging**
