### PR TITLE
First Task Completed 

### PR DESCRIPTION
**Pull request by Magalakshmiravi**

### CODE REVIEW

**Comment by tamilarasumk731** [comment]
@Magalakshmiravi Good. But you should follow the standards of electron js. 
The script should not be in the index file and the HTML tags should not be hardcoded in the index file. 
You should render it from the script file.

CC: @AkbarHabeeb @InbasasiS @smartsri18

**Comment by Magalakshmiravi** [comment]
> @Magalakshmiravi Good. But you should follow the standards of electron js.
> The script should not be in the index file and the HTML tags should not be hardcoded in the index file.
> You should render it from the script file.
> 
> CC: @AkbarHabeeb @InbasasiS @smartsri18

@tamilarasumk731  ok na..,

**Comment by tamilarasumk731** [comment]
@Magalakshmiravi Update your status? 

CC: @AkbarHabeeb @InbasasiS @smartsri18

**Comment by AkbarHabeeb** [comment]
@tamilarasumk731 If new PR opened, you can close this da.

**Pull request closed without merging**
