### PR TITLE
React Portfolio

### PR DESCRIPTION
**Pull request by aravind-cod-101**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@aravind-cod-101 Can you add a screenshot of your work

**Comment by aravind-cod-101** [comment]
> @aravind-cod-101 Can you add a screenshot of your work

**Comment by aravind-cod-101** [comment]
> @aravind-cod-101 Can you add a screenshot of your work

**Comment by AkbarHabeeb** [comment]
@aravind-cod-101 Stunning. Happy to see this.
cc: @Inbasasi @tamilarasumk731 @smartsri18 @JayapradhaV @Kishor-Kumar07 @dineshkumar6688

**Comment by AkbarHabeeb** [comment]
@aravind-cod-101 I find too much of font awesome imports and variables. May be you can truncate them.

**Comment by aravind-cod-101** [comment]
> @aravind-cod-101 Stunning. Happy to see this.
> cc: @Inbasasi @tamilarasumk731 @smartsri18 @JayapradhaV @Kishor-Kumar07 @dineshkumar6688 

Thanks na ✨

**Comment by aravind-cod-101** [comment]
> @aravind-cod-101 I find too much of font awesome imports and variables. May be you can truncate them.

Ok na

**Pull request merged**
