### PR TITLE
fetched news using news-api

### PR DESCRIPTION
**Pull request by poomathi03**
Fetched news using New-api  ruby client library

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@tamilarasumk731

**Comment by tamilarasumk731** [comment]
@poomathi03 Good job. But you need to do some more work on extracting the data from the response.
Process the response:
Extract the title, description, url, source name from each article in api resonse.

**Comment by AkbarHabeeb** [comment]
@poomathi03 Its nice. For a beginner, @tamilarasumk731 and @Inbasasi encourage you to do it manually, rather than using the gem file.

**Comment by AkbarHabeeb** [comment]
@poomathi03 If you are struck, please let us know ur doubts. 
cc: @smartsri18

**Pull request merged**
