### PR TITLE
GIT

### PR DESCRIPTION
**Pull request by shruthi120**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@shruthi120 Add the files as per the guidelines given in the readme file. And your file was empty, please check that.

**Comment by shruthi120** [comment]
ok na i ll check it sry na

**Comment by shruthi120** [comment]
[GIT.docx](https://github.com/Team-Tomato/Learn/files/4616772/GIT.docx)

**Comment by AkbarHabeeb** [comment]
@shruthi120 Please get help from anyone of ur classmates or 3rd years sis. And push as per the standard we follow in our team.

**Pull request closed without merging**
