### PR TITLE
PYTHON TASKS

### PR DESCRIPTION
**Pull request by BARANI2001**
Day 3:Matrix Multiplication
 Day 4:Write a python function to reverse a string

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@BARANI2001 Why you are adding the same files outside your folder also. Please delete them and update the PR

**Comment by AkbarHabeeb** [comment]
@hariharan333

**Comment by AkbarHabeeb** [comment]
@hariharan333 Please check the above comment

**Comment by BARANI2001** [comment]
@AkbarHabeeb I'll check it & update it soon anna

**Pull request closed without merging**
