### PR TITLE
displayed contributors commit count

### PR DESCRIPTION
**Pull request by keerthinayana**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@keerthinayana Nice one sis. Can you confirm the deletion of the projectpage js file.

**Comment by keerthinayana** [comment]
By mistake I deleted it na.

**Comment by AkbarHabeeb** [comment]
@keerthinayana okie. Can you add that file sis

**Comment by keerthinayana** [comment]
added @AkbarHabeeb anna

**Comment by AkbarHabeeb** [comment]
@keerthinayana  Merging it

**Pull request merged**
