### PR TITLE
Python Flask -Api task

### PR DESCRIPTION
**Pull request by SangeeRajan**

### CODE REVIEW

**Comment by InbasasiS** [comment]
@SangeeRajan Changes looks good.
Why you removed the files of your previous task?
cc: @tamilarasumk731 @AkbarHabeeb

**Comment by tamilarasumk731** [comment]
@SangeeRajan Can you please add those files? Otherwise, It will be removed from the Learn repo.

And Can you refer our Backend repo for flask? Make the changes.

cc: @InbasasiS @AkbarHabeeb @smartsri18

**Comment by SangeeRajan** [comment]
> @SangeeRajan Changes looks good.
> Why you removed the files of your previous task?
> cc: @tamilarasumk731 @AkbarHabeeb

**Comment by SangeeRajan** [comment]
> _No description provided._

**Comment by SangeeRajan** [comment]
> @SangeeRajan Changes looks good.
> Why you removed the files of your previous task?
> cc: @tamilarasumk731 @AkbarHabeeb

>@InbasasiS  I have made the changes 
>cc:@tamilarasumk731 @AkbarHabeeb

**Comment by InbasasiS** [comment]
Now looks good @SangeeRajan 
Merging it 
cc: @AkbarHabeeb @tamilarasumk731 @smartsri18

**Pull request merged**
