### PR TITLE
Kadane's Algorithm

### PR DESCRIPTION
**Pull request by shruthi120**

### CODE REVIEW

**Review by VigneshKarthigeyan — APPROVED** [review]
Good work @shruthi120 
Logic is right but have some compiler mistakes in code.
Try to raise a pr with clean code next time.

**Comment by shruthi120** [comment]
ok na sure na
compiler mistakes means what kind of na i have checked for some of the inputs it worked crtly na

**Review by VigneshKarthigeyan — APPROVED** [review]

**Comment by VigneshKarthigeyan** [comment]
check line no. 19 @shruthi120

**Comment by shruthi120** [comment]
Sry na main typo error actually i have done 2 projects for 2 diff ways by mistake i have chosen this file. Hereafter i ll not make these mistakes. Thanks na

**Comment by InbasasiS** [comment]
Good Work @shruthi120 Note down their comments
Move on to your next tasks

**Comment by shruthi120** [comment]
sure na thanks na

**Pull request merged**
